name: mars
channels:
  - intel
  - defaults
dependencies:
  - bzip2=1.0.8=0
  - certifi=2019.9.11=py37_0
  - intelpython=2020.0=1
  - libffi=3.2.1=11
  - openssl=1.1.1d=0
  - pip=19.1.1=py37_0
  - python=3.7.4=3
  - setuptools=41.0.1=py37_0
  - sqlite=3.29.0=0
  - tcl=8.6.4=24
  - tk=8.6.4=29
  - wheel=0.31.0=py37_3
  - xz=5.2.4=h1de35cc_7
  - zlib=1.2.11=h1de35cc_7
  - pip:
    - appnope==0.1.0
    - arviz==0.6.1
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.0
    - cftime==1.0.4.2
    - cycler==0.10.0
    - decorator==4.4.1
    - defusedxml==0.6.0
    - entrypoints==0.3
    - h5py==2.10.0
    - importlib-metadata==1.4.0
    - ipykernel==5.1.3
    - ipython==7.11.1
    - ipython-genutils==0.2.0
    - jedi==0.15.2
    - jinja2==2.10.3
    - json5==0.8.5
    - jsonschema==3.2.0
    - jupyter-client==5.3.4
    - jupyter-core==4.6.1
    - jupyterlab==1.2.5
    - jupyterlab-server==1.0.6
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mistune==0.8.4
    - more-itertools==8.1.0
    - nbconvert==5.6.1
    - nbformat==5.0.3
    - netcdf4==1.5.3
    - notebook==6.0.2
    - numpy==1.18.1
    - packaging==20.0
    - pandas==0.25.3
    - pandocfilters==1.4.2
    - parso==0.5.2
    - patsy==0.5.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.2
    - ptyprocess==0.6.0
    - pygments==2.5.2
    - pymc3==3.8
    - pyparsing==2.4.6
    - pyrsistent==0.15.7
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pyzmq==18.1.1
    - scipy==1.4.1
    - send2trash==1.5.0
    - six==1.14.0
    - terminado==0.8.3
    - testpath==0.4.4
    - theano==1.0.4
    - tornado==6.0.3
    - tqdm==4.41.1
    - traitlets==4.3.3
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - xarray==0.14.1
    - zipp==2.0.0
